### Questions

In [1]:
# 1. Import the package numpy as np
import numpy as np 

In [2]:
# 2. Create 1D array "a1" from the list and display the properties
a1 = [10,20,30,40,50]
for i in a1 :
    print (i)
    i= i+1

10
20
30
40
50


In [3]:
# 3. Create 2D array "a2" of one digit random numbers with shape (4, 5) and display the propertiesa
a2 = np.arange(20).reshape(4,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
# 4. Get only first row from a2
a2[0]

array([0, 1, 2, 3, 4])

In [5]:
# 5. Get only last column from a2
a2[:, [4]]

array([[ 4],
       [ 9],
       [14],
       [19]])

In [6]:
# 6. Get the value at position 2, 4
a2[2,4]

14

In [7]:
# 7. Get the data from first two rows and last three columns. Hint : [ start : end : step ]
a2[0: 2 : 1, [2,3,4]]

array([[2, 3, 4],
       [7, 8, 9]])

In [8]:
# 8. Add number 100 to elements in array a2
a2+100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [9]:
# 9. get the values which are greatet than the overall average
a3 = a2.mean()
a2[a2 > a3 ]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
# 10. Create a numpy array a3 with 20 equidistant elements in range 1, 5
a4 = np.linspace(1,5,20)
a4

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
# 11. Create (3, 5) ndarray with numbers starting 11 till 25 (numbers should not repeat) & save in a4
a5 = np.linspace(11,25, 15)
a5.reshape(3,5)

array([[11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [12]:
# 12. Get the values from a4 which are less than 15 and greater than 20

In [13]:
a5[(a5 > 15) & (a5<20)]

array([16., 17., 18., 19.])